version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: instagram_bot_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - instagram-bot-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s

  app:
    build: .
    container_name: instagram_bot
    restart: unless-stopped
    volumes:
      - .:/app
      - ./sessions:/app/sessions
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      # اضافه کردن متغیر محیطی DATABASE_URL
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - instagram-bot-network
    command: >
      bash -c "
      echo 'منتظر آماده شدن دیتابیس...' &&
      sleep 20 &&
      python db_recovery.py &&
      echo 'در حال شروع برنامه اصلی...' &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

networks:
  instagram-bot-network:
    driver: bridge